# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_upload_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='username',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
