# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20160610_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='linktype',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
