# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_upload_linktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
