# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20160612_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='file',
            new_name='source',
        ),
    ]
