# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20160612_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='source',
        ),
    ]
