# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_upload_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
