# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_upload_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
