# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20160721_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
    ]
