# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20160721_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='current_exp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='user_photo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
