# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_account_tagline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
