# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20160722_2322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
