# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=6)),
                ('date_of_birth', models.DateField()),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=45, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.CharField(blank=True, max_length=5000, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
