# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20160723_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
